# -*- coding: utf-8 -*-
"""1817051001_1817051033_tubesAI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108MU9yCGZZc74LDKeLkUwptr2byaOn3g
"""

from sklearn import tree
import pandas as pd
import pydotplus
from IPython.display import Image

ds = pd.read_csv('tubes.csv')
ds.head()

buah = pd.get_dummies(ds[['Tekstur','warna','bau']])
buah

hasil = tree.DecisionTreeClassifier(criterion='entropy')
hasil_train = hasil.fit(buah, ds['busuk'])

print(tree.export_graphviz(hasil_train,None))
dot_data = tree.export_graphviz(hasil_train, out_file=None, feature_names=list(buah.columns.values),
                                class_names=['tidak busuk','busuk'], rounded=True, filled=True)
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())